language: node_js
sudo: false
cache: yarn
node_js:
  - "7.10"
  - "8"
install:
  - yarn install
script:
  - yarn test -- --coverage --forceExit --runInBand --no-cache
  - yarn run codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: "developer@rilix.com.br"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
